'use client';

import React, { useState, useEffect } from 'react';
import { PageHeader } from "@/components/common/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger, DialogFooter, DialogClose } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { UserPlus, Edit, Trash2, Loader2, ShieldAlert, ClipboardCopy } from "lucide-react";
import { getUsers, adminCreateUserProfile, adminUpdateUserProfile, type User, AdminUserFormSchema, type AdminUserFormData } from '@/services/user';
import { useAuth } from '@/contexts/auth-context';
import { useToast } from '@/hooks/use-toast';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm, Controller } from 'react-hook-form';
import { format } from 'date-fns';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';


export default function UsersPage() {
  const { currentUser } = useAuth();
  const [users, setUsers] = useState<User[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [editingUser, setEditingUser] = useState<User | null>(null);
  const { toast } = useToast();
  const [createdUserId, setCreatedUserId] = useState<string | null>(null); // Store ID after creation

  const form = useForm<AdminUserFormData>({
    resolver: zodResolver(AdminUserFormSchema),
    defaultValues: {
      name: "",
      email: "",
      role: "student", // Default role for new user form
      schoolId: currentUser?.role === 'school_admin' ? currentUser.schoolId : undefined,
      // No authUid input here as it's generated by Firestore now
    },
  });

 useEffect(() => {
    if (currentUser?.role === 'superadmin' || currentUser?.role === 'school_admin') {
        fetchUsers();
    } else {
        setIsLoading(false); // Not allowed to view
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentUser]);

  useEffect(() => {
    if (editingUser) {
      form.reset({
        id: editingUser.id, // Include existing ID when editing
        name: editingUser.name,
        email: editingUser.email || '',
        role: editingUser.role as 'student' | 'teacher' | 'school_admin', // Cast assumes valid roles are stored
        schoolId: editingUser.schoolId,
        // No authUid needed for edit form
      });
    } else {
      form.reset({ // Reset to default for new user
          name: "",
          email: "",
          role: "student",
          schoolId: currentUser?.role === 'school_admin' ? currentUser.schoolId : undefined,
          // No authUid field here
      });
    }
  }, [editingUser, form, currentUser]);


  const fetchUsers = async () => {
    setIsLoading(true);
    try {
      const fetchedUsers = await getUsers(currentUser?.role === 'school_admin' ? currentUser.schoolId : undefined);
      setUsers(fetchedUsers);
    } catch (error) {
      console.error("Error fetching users:", error);
      toast({ title: "Error", description: "Could not fetch users.", variant: "destructive" });
    } finally {
      setIsLoading(false);
    }
  };

 const handleEditClick = (user: User) => {
    setEditingUser(user);
    setCreatedUserId(null); // Clear created ID when editing
    setIsEditDialogOpen(true);
  };

 const handleAddNewClick = () => {
    setEditingUser(null); // Clear editing state
    setCreatedUserId(null); // Clear created ID
    setIsEditDialogOpen(true); // Open dialog
  };

 const handleDialogClose = (open: boolean) => {
    if (!open) {
      setEditingUser(null); // Clear editing state when dialog closes
      setCreatedUserId(null); // Clear created ID
      form.reset({ // Reset form to defaults based on current user role
        name: "",
        email: "",
        role: "student",
        schoolId: currentUser?.role === 'school_admin' ? currentUser.schoolId : undefined,
      });
      setIsEditDialogOpen(false);
    } else {
       setIsEditDialogOpen(true);
    }
  };

   // Function to copy text to clipboard
  const copyToClipboard = (text: string) => {
      if (!text) return;
      navigator.clipboard.writeText(text).then(() => {
        toast({ title: "User ID Copied!", description: "You can now use this as the UID when creating the Firebase Auth user." });
      }).catch(err => {
        toast({ title: "Copy failed", description: "Could not copy User ID.", variant: "destructive" });
        console.error('Failed to copy text: ', err);
      });
    };

  async function onSubmit(values: AdminUserFormData) {
    if (!currentUser) return;
    setIsSubmitting(true);
    setCreatedUserId(null); // Clear previous created ID

    try {
      let resultUser: User;
      if (editingUser) {
         // Ensure id exists for update operation
         if (!editingUser.id) throw new Error("Editing user ID is missing.");
         // Pass the existing ID explicitly for update
         console.log("Updating user:", editingUser.id, values)
         resultUser = await adminUpdateUserProfile(editingUser.id, values, currentUser.role, currentUser.schoolId);
         toast({ title: "User Updated", description: `${resultUser.name}'s profile has been updated.` });
         fetchUsers(); // Refresh list after update
         handleDialogClose(false); // Close dialog after successful update
      } else {
         // For creation, adminCreateUserProfile generates the ID internally
         const dataToSend = { ...values };
         // Ensure school admin assigns to their school if not superadmin
         if (currentUser.role === 'school_admin' && !dataToSend.schoolId) {
            dataToSend.schoolId = currentUser.schoolId;
         }
         console.log("Creating user profile with data:", dataToSend)
         resultUser = await adminCreateUserProfile(dataToSend, currentUser.role, currentUser.schoolId);

         // Store the created user ID to display in the alert
         setCreatedUserId(resultUser.id);

         toast({
            title: "Firestore Profile Created!",
            description: `Profile for ${resultUser.name} created. Now create the Firebase Auth user.`,
            duration: 5000
         });
          // Don't close the dialog immediately, show the success/instruction alert
          fetchUsers(); // Refresh list in background
      }

    } catch (error: any) {
      console.error("Error submitting user form:", error);
      toast({
        title: editingUser ? "Update Failed" : "Creation Failed",
        description: error.message || "An unknown error occurred.",
        variant: "destructive",
        duration: 7000
      });
    } finally {
      // Keep dialog open on creation success to show instructions/copy button
      if (!editingUser && createdUserId) {
         // Do nothing, let the user close manually after seeing the ID
      } else {
        // Close dialog on update success or any failure
        // handleDialogClose(false); - Let finally handle this part
      }
      setIsSubmitting(false); // Always reset submitting state

      // Close dialog only if it was an update or if creation failed
      if (editingUser || (!editingUser && !createdUserId && !isSubmitting)) {
         handleDialogClose(false);
      }
    }
  }


  if (isLoading) {
    return (
      <div className="flex justify-center items-center h-64">
        <Loader2 className="h-12 w-12 animate-spin text-primary" />
      </div>
    );
  }

  if (!currentUser || (currentUser.role !== 'superadmin' && currentUser.role !== 'school_admin')) {
    return (
      <>
        <PageHeader title="User Management" description="You do not have permission to manage users." />
         <Card className="mt-6">
            <CardContent className="pt-6 text-center text-muted-foreground">
                <ShieldAlert className="h-12 w-12 mx-auto text-destructive mb-2" />
                Access Denied. You do not have the necessary permissions to view this page.
            </CardContent>
        </Card>
      </>
    );
  }

  const allowedRoles = currentUser.role === 'superadmin'
      ? ['student', 'teacher', 'school_admin']
      : ['student', 'teacher'];

  return (
    <>
      <PageHeader
        title="User Management"
        description={currentUser.role === 'superadmin' ? "Administer all user accounts." : `Manage users for ${currentUser.schoolName || 'your school'}.`}
        actions={
          // Use handleAddNewClick to ensure state is reset correctly for Add New
          <Button onClick={handleAddNewClick}>
            <UserPlus className="mr-2 h-4 w-4" /> Add New User Profile
          </Button>
        }
      />

      <Dialog open={isEditDialogOpen} onOpenChange={(open) => handleDialogClose(open)}>
        {/* DialogTrigger is now handled by the Add New button above */}
        {/* <DialogTrigger asChild>...</DialogTrigger> */}
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>{editingUser ? 'Edit User Profile' : 'Add New User Profile'}</DialogTitle>
            <DialogDescription>
              {editingUser ? `Update ${editingUser.name}'s profile.` : "Create a new user profile in Firestore. Remember to create the Firebase Auth user manually afterwards using the generated Firestore ID."}
            </DialogDescription>
          </DialogHeader>

          {/* Show instructions only when creating a new user AND profile creation was successful */}
           {!editingUser && createdUserId && (
               <Alert variant="default" className="mt-4 bg-green-100 border-green-300 dark:bg-green-900 dark:border-green-700">
                 <ShieldAlert className="h-4 w-4 text-green-700 dark:text-green-300" />
                 <AlertTitle className="text-green-800 dark:text-green-200">Success &amp; Next Step: Create Firebase Auth User</AlertTitle>
                 <AlertDescription className="text-green-700 dark:text-green-300 space-y-2">
                     <p>Firestore profile created successfully!</p>
                     <p>Now, manually create the Firebase Authentication user in the Firebase Console:</p>
                      <ul className="list-disc list-inside pl-4 text-sm">
                            <li>Use Email: <strong className="font-mono">{form.getValues('email')}</strong></li>
                            <li>Set a Password.</li>
                             <li>
                                <strong className="font-bold text-destructive">IMPORTANT:</strong> Set the <strong className="font-bold text-primary">User UID</strong> to the following ID:
                                <div className="flex items-center gap-2 mt-1 p-1 bg-muted rounded">
                                    <code className="font-mono text-sm text-primary flex-grow">{createdUserId}</code>
                                    <Button
                                      type="button"
                                      variant="ghost"
                                      size="sm"
                                      onClick={() => copyToClipboard(createdUserId)}
                                      title="Copy User ID"
                                      className="px-2"
                                    >
                                      <ClipboardCopy className="h-4 w-4" />
                                    </Button>
                                </div>
                             </li>
                        </ul>
                       <p className="text-xs">This links the login to this Firestore profile and role.</p>
                       <p className="mt-2">You can close this dialog now.</p>
                 </AlertDescription>
               </Alert>
          )}

            {/* Show the initial instruction only when creating and before successful submission */}
            {!editingUser && !createdUserId && (
                 <Alert variant="destructive" className="mt-4">
                   <ShieldAlert className="h-4 w-4" />
                   <AlertTitle>Manual Firebase Auth Step Required Afterwards</AlertTitle>
                   <AlertDescription>
                       After saving this profile, you <strong className="font-bold">MUST MANUALLY CREATE</strong> the corresponding Firebase Authentication user.
                       Use the <strong className="font-bold">email specified below</strong>. The <strong className="font-bold text-primary">User UID MUST be set to the Firestore Document ID</strong>, which will be shown in the success message after you save this form.
                   </AlertDescription>
                 </Alert>
            )}

            {/* Hide form if creation was successful to prevent accidental resubmission */}
            {(!createdUserId || editingUser) && (
                <form onSubmit={form.handleSubmit(onSubmit)} className="grid gap-4 py-4">
                    {/* Email is editable only during creation */}
                    {!editingUser && (
                        <FormField
                            control={form.control}
                            name="email"
                            render={({ field }) => (
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="email" className="text-right">Email</Label>
                                <Input id="email" {...field} className="col-span-3" placeholder="user@example.com" type="email" />
                                <span className="col-start-2 col-span-3"><FormMessage /></span>
                            </div>
                            )}
                        />
                    )}
                    {/* Display email as read-only when editing */}
                    {editingUser && (
                        <div className="grid grid-cols-4 items-center gap-4">
                            <Label htmlFor="email-display" className="text-right">Email</Label>
                            <Input id="email-display" value={editingUser.email || ''} className="col-span-3 bg-muted" readOnly disabled title="Email cannot be changed after creation." />
                        </div>
                    )}
                    <FormField
                    control={form.control}
                    name="name"
                    render={({ field }) => (
                        <div className="grid grid-cols-4 items-center gap-4">
                        <Label htmlFor="name" className="text-right">Name</Label>
                        <Input id="name" {...field} className="col-span-3" placeholder="Full Name" />
                        <span className="col-start-2 col-span-3"><FormMessage /></span>
                        </div>
                    )}
                    />
                    <FormField
                    control={form.control}
                    name="role"
                    render={({ field }) => (
                        <div className="grid grid-cols-4 items-center gap-4">
                        <Label htmlFor="role" className="text-right">Role</Label>
                            <Controller
                                control={form.control}
                                name="role"
                                render={({ field: controllerField, fieldState }) => (
                                <Select
                                    onValueChange={controllerField.onChange}
                                    value={controllerField.value}
                                    // Disable role change if editing the primary superadmin,
                                    // or if a school admin tries to edit another school admin.
                                    disabled={(editingUser?.id === 'superadmin') || (currentUser?.role === 'school_admin' && editingUser?.role === 'school_admin')}
                                >
                                    <SelectTrigger id="role" className="col-span-3">
                                        <SelectValue placeholder="Select a role" />
                                    </SelectTrigger>
                                    <SelectContent>
                                    {allowedRoles.map(roleOption => (
                                        <SelectItem
                                        key={roleOption}
                                        value={roleOption}
                                        // Prevent school admin from CREATING another school admin
                                        disabled={roleOption === 'school_admin' && currentUser?.role === 'school_admin' && !editingUser}
                                        >
                                            {roleOption.charAt(0).toUpperCase() + roleOption.slice(1).replace('_', ' ')}
                                        </SelectItem>
                                    ))}
                                    </SelectContent>
                                </Select>
                                )}
                            />
                            <span className="col-start-2 col-span-3"><FormMessage /></span>
                        </div>
                    )}
                    />
                    {/* School ID Input for Superadmin */}
                    {currentUser.role === 'superadmin' && (
                        <FormField
                        control={form.control}
                        name="schoolId"
                        render={({ field }) => (
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="schoolId" className="text-right">School ID</Label>
                                <Input
                                    id="schoolId"
                                    {...field}
                                    value={field.value || ""} // Ensure controlled component has a string value
                                    className="col-span-3"
                                    placeholder="Enter School ID (if applicable)"
                                    // Disable if the role being set/edited is 'superadmin'
                                    disabled={form.getValues('role') === 'superadmin' || editingUser?.role === 'superadmin'}
                                />
                                <span className="col-start-2 col-span-3"><FormMessage /></span>
                            </div>
                        )}
                        />
                    )}
                    {/* Display School ID for School Admin (read-only) */}
                     {currentUser.role === 'school_admin' && (
                         <div className="grid grid-cols-4 items-center gap-4">
                             <Label htmlFor="schoolId-display" className="text-right">School</Label>
                             <Input
                                id="schoolId-display"
                                value={currentUser.schoolName ? `${currentUser.schoolName} (${currentUser.schoolId})` : currentUser.schoolId || 'N/A'}
                                className="col-span-3 bg-muted"
                                readOnly
                                disabled
                                title="Users will be assigned to your school."/>
                         </div>
                     )}
                    <DialogFooter>
                        <DialogClose asChild>
                            <Button type="button" variant="outline">Cancel</Button>
                        </DialogClose>
                    <Button type="submit" disabled={isSubmitting}>
                        {isSubmitting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : (editingUser ? 'Save Changes' : 'Create Profile')}
                    </Button>
                    </DialogFooter>
                </form>
            )}
            {/* Show only close button after successful creation */}
            {!editingUser && createdUserId && (
                 <DialogFooter className="mt-4">
                     <DialogClose asChild>
                         <Button type="button" variant="outline">Close</Button>
                     </DialogClose>
                 </DialogFooter>
            )}
        </DialogContent>
      </Dialog>


      {/* User Table */}
      {users.length === 0 && !isLoading ? (
         <Card className="mt-6">
             <CardContent className="pt-6 text-center text-muted-foreground">
                 No users found{currentUser?.role === 'school_admin' ? ` for ${currentUser.schoolName}` : ''}. Click "Add New User Profile" to start.
             </CardContent>
         </Card>
      ) : (
        <Card className="mt-6 shadow-lg">
          <CardHeader>
            <CardTitle className="text-primary">User List</CardTitle>
            <CardDescription>
                {currentUser?.role === 'superadmin' ? 'All users in the system.' : `Users associated with ${currentUser.schoolName || 'your school'}.`}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Name</TableHead>
                  <TableHead>Email</TableHead>
                  <TableHead>Role</TableHead>
                  <TableHead>School</TableHead>
                   <TableHead>User ID (Auth UID)</TableHead>
                  <TableHead>Created At</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {users.map((user) => (
                  <TableRow key={user.id}>
                    <TableCell className="font-medium">{user.name}</TableCell>
                    <TableCell>{user.email}</TableCell>
                    <TableCell>{user.role?.charAt(0).toUpperCase() + user.role?.slice(1).replace('_', ' ') || 'N/A'}</TableCell>
                    <TableCell>{user.schoolName || (user.role === 'superadmin' ? 'N/A (Global)' : (user.schoolId ? `ID: ${user.schoolId}` : 'N/A'))}</TableCell>
                     <TableCell className="font-mono text-xs">
                       {user.id}
                       <Button
                          variant="ghost"
                          size="icon"
                          className="ml-1 h-5 w-5"
                          onClick={() => copyToClipboard(user.id)}
                          title="Copy User ID"
                       >
                         <ClipboardCopy className="h-3 w-3"/>
                       </Button>
                       </TableCell>
                    <TableCell>{user.createdAt ? format(new Date(user.createdAt), 'PP') : 'N/A'}</TableCell>
                    <TableCell className="text-right">
                      <Button
                        variant="ghost"
                        size="icon"
                        onClick={() => handleEditClick(user)}
                        // Only superadmin can edit the primary 'superadmin' UID profile.
                        disabled={user.id === 'superadmin' && currentUser?.id !== 'superadmin'}
                       >
                        <Edit className="h-4 w-4" />
                        <span className="sr-only">Edit</span>
                      </Button>
                       {/* Optional: Add Delete Button (with confirmation) - Needs careful implementation */}
                       {/* <Button
                          variant="ghost"
                          size="icon"
                          className="text-destructive hover:text-destructive/80"
                          disabled={user.id === 'superadmin'} // Cannot delete primary superadmin
                          onClick={() => { /* Implement delete confirmation and logic */ }}
                        >
                          <Trash2 className="h-4 w-4" />
                           <span className="sr-only">Delete</span>
                       </Button> */}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      )}
    </>
  );
}

