#!/bin/bash

# Deploy Firestore Rules to Firebase
# This script helps you deploy the updated rules

echo "🔥 Firestore Rules Deployment Guide"
echo "===================================="
echo ""
echo "📋 MANUAL DEPLOYMENT (Recommended)"
echo ""
echo "1. Go to Firebase Console:"
echo "   https://console.firebase.google.com/project/campusconnect-pro-61eqk/firestore/rules"
echo ""
echo "2. Replace the rules with the content from:"
echo "   /workspaces/CampusConnect/firestore.rules"
echo ""
echo "3. Click 'Publish'"
echo ""
echo "-----------------------------------"
echo ""
echo "🤖 AUTOMATIC DEPLOYMENT (Optional)"
echo ""
echo "If you want to use Firebase CLI:"
echo ""
echo "1. Install Firebase CLI:"
echo "   npm install -g firebase-tools"
echo ""
echo "2. Login to Firebase:"
echo "   firebase login"
echo ""
echo "3. Deploy rules:"
echo "   firebase deploy --only firestore:rules"
echo ""
echo "-----------------------------------"
echo ""
echo "✅ WHAT WAS FIXED"
echo ""
echo "Old rule:"
echo "  allow create: if isSchoolAdmin();"
echo ""
echo "New rule:"
echo "  allow create: if isSignedIn() && userId == request.auth.uid;"
echo ""
echo "Why: Users need to create their own profile on first login"
echo "     The old rule created a circular dependency"
echo ""
